import { PrismaClient } from '@prisma/client';
import dotenv from 'dotenv';

dotenv.config();

// Prisma 6 reads DATABASE_URL from environment automatically
const prisma = new PrismaClient();

const danangLocations = [
  // Beaches
  {
    name: 'My Khe Beach',
    description: 'One of the most beautiful beaches in Vietnam, perfect for swimming and water sports.',
    address: 'My Khe Beach, Da Nang, Vietnam',
    latitude: 16.0472,
    longitude: 108.2478,
    category: 'beach',
    subcategory: 'swimming',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    rating: 4.8,
    priceRange: 'low',
    indoor: false,
    outdoor: true,
    weatherDependent: true,
    isAnvaAuthentic: false,
    localRating: 4.7,
  },
  {
    name: 'Non Nuoc Beach',
    description: 'Pristine beach with white sand and clear blue water, less crowded than My Khe.',
    address: 'Non Nuoc Beach, Da Nang, Vietnam',
    latitude: 16.0167,
    longitude: 108.2333,
    category: 'beach',
    subcategory: 'swimming',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    rating: 4.6,
    priceRange: 'low',
    indoor: false,
    outdoor: true,
    weatherDependent: true,
    isAnvaAuthentic: true,
    localRating: 4.8,
  },
  {
    name: 'Bac My An Beach',
    description: 'Quiet beach area popular with locals, great for relaxation.',
    address: 'Bac My An, Da Nang, Vietnam',
    latitude: 16.0333,
    longitude: 108.2500,
    category: 'beach',
    subcategory: 'relaxation',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    rating: 4.5,
    priceRange: 'low',
    indoor: false,
    outdoor: true,
    weatherDependent: true,
    isAnvaAuthentic: true,
    localRating: 4.6,
  },

  // Temples & Culture
  {
    name: 'Linh Ung Pagoda',
    description: 'Famous pagoda with a 67-meter tall Lady Buddha statue overlooking the sea.',
    address: 'Son Tra Peninsula, Da Nang, Vietnam',
    latitude: 16.1000,
    longitude: 108.2167,
    category: 'temple',
    subcategory: 'buddhist',
    imageUrl: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800',
    rating: 4.7,
    priceRange: 'low',
    indoor: true,
    outdoor: true,
    weatherDependent: false,
    isAnvaAuthentic: true,
    localRating: 4.8,
  },
  {
    name: 'Cao Dai Temple',
    description: 'Colorful temple representing the Cao Dai religion, unique architecture.',
    address: 'Da Nang, Vietnam',
    latitude: 16.0667,
    longitude: 108.2167,
    category: 'temple',
    subcategory: 'cao_dai',
    imageUrl: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800',
    rating: 4.5,
    priceRange: 'low',
    indoor: true,
    outdoor: false,
    weatherDependent: false,
    isAnvaAuthentic: true,
    localRating: 4.6,
  },
  {
    name: 'Da Nang Museum of Cham Sculpture',
    description: 'Museum showcasing Cham culture and artifacts, one of the finest collections in Vietnam.',
    address: '1 Trung Nu Vuong, Da Nang, Vietnam',
    latitude: 16.0667,
    longitude: 108.2167,
    category: 'museum',
    subcategory: 'culture',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    rating: 4.6,
    priceRange: 'medium',
    indoor: true,
    outdoor: false,
    weatherDependent: false,
    isAnvaAuthentic: true,
    localRating: 4.7,
  },

  // Food & Restaurants
  {
    name: 'Banh Xeo Ba Duong',
    description: 'Famous local restaurant serving authentic Vietnamese pancakes (banh xeo).',
    address: '280/23 Hoang Dieu, Da Nang, Vietnam',
    latitude: 16.0667,
    longitude: 108.2167,
    category: 'restaurant',
    subcategory: 'local',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    rating: 4.8,
    priceRange: 'low',
    indoor: true,
    outdoor: false,
    weatherDependent: false,
    isAnvaAuthentic: true,
    localRating: 4.9,
  },
  {
    name: 'Mi Quang Ba Mua',
    description: 'Local favorite for Mi Quang noodles, a Danang specialty dish.',
    address: '19 Tran Binh Trong, Da Nang, Vietnam',
    latitude: 16.0667,
    longitude: 108.2167,
    category: 'restaurant',
    subcategory: 'local',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    rating: 4.7,
    priceRange: 'low',
    indoor: true,
    outdoor: false,
    weatherDependent: false,
    isAnvaAuthentic: true,
    localRating: 4.8,
  },
  {
    name: 'Waterfront Restaurant',
    description: 'Upscale restaurant with beautiful sea views, serving Vietnamese and international cuisine.',
    address: 'Bach Dang Street, Da Nang, Vietnam',
    latitude: 16.0667,
    longitude: 108.2167,
    category: 'restaurant',
    subcategory: 'fine_dining',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    rating: 4.5,
    priceRange: 'high',
    indoor: true,
    outdoor: true,
    weatherDependent: false,
    isAnvaAuthentic: false,
    localRating: 4.3,
  },

  // Markets & Shopping
  {
    name: 'Han Market',
    description: 'Large traditional market selling local products, souvenirs, and street food.',
    address: '119 Tran Phu, Da Nang, Vietnam',
    latitude: 16.0667,
    longitude: 108.2167,
    category: 'market',
    subcategory: 'shopping',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    rating: 4.4,
    priceRange: 'low',
    indoor: true,
    outdoor: false,
    weatherDependent: false,
    isAnvaAuthentic: true,
    localRating: 4.6,
  },
  {
    name: 'Con Market',
    description: 'Local market popular with residents, great for authentic food and shopping.',
    address: 'Ong Ich Khiem, Da Nang, Vietnam',
    latitude: 16.0667,
    longitude: 108.2167,
    category: 'market',
    subcategory: 'local',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    rating: 4.6,
    priceRange: 'low',
    indoor: true,
    outdoor: false,
    weatherDependent: false,
    isAnvaAuthentic: true,
    localRating: 4.8,
  },

  // Nature & Activities
  {
    name: 'Marble Mountains',
    description: 'Five limestone hills with caves, pagodas, and stunning views of the coastline.',
    address: 'Hoa Hai, Da Nang, Vietnam',
    latitude: 16.0000,
    longitude: 108.2667,
    category: 'attraction',
    subcategory: 'nature',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    rating: 4.7,
    priceRange: 'medium',
    indoor: true,
    outdoor: true,
    weatherDependent: true,
    isAnvaAuthentic: true,
    localRating: 4.8,
  },
  {
    name: 'Ba Na Hills',
    description: 'Mountain resort with cable car, French village, and Golden Bridge.',
    address: 'Hoa Ninh, Da Nang, Vietnam',
    latitude: 15.9833,
    longitude: 108.0167,
    category: 'attraction',
    subcategory: 'theme_park',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    rating: 4.6,
    priceRange: 'high',
    indoor: true,
    outdoor: true,
    weatherDependent: true,
    isAnvaAuthentic: false,
    localRating: 4.4,
  },
  {
    name: 'Son Tra Peninsula',
    description: 'Mountainous peninsula with pristine nature, hiking trails, and wildlife.',
    address: 'Son Tra Peninsula, Da Nang, Vietnam',
    latitude: 16.1167,
    longitude: 108.2333,
    category: 'attraction',
    subcategory: 'nature',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    rating: 4.8,
    priceRange: 'low',
    indoor: false,
    outdoor: true,
    weatherDependent: true,
    isAnvaAuthentic: true,
    localRating: 4.9,
  },

  // Nightlife
  {
    name: 'Sky36 Rooftop Bar',
    description: 'Highest rooftop bar in Da Nang with panoramic city views and cocktails.',
    address: '36 Bach Dang, Da Nang, Vietnam',
    latitude: 16.0667,
    longitude: 108.2167,
    category: 'nightlife',
    subcategory: 'bar',
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    rating: 4.5,
    priceRange: 'high',
    indoor: true,
    outdoor: true,
    weatherDependent: false,
    isAnvaAuthentic: false,
    localRating: 4.2,
  },
  {
    name: 'Local Beer Street',
    description: 'Street lined with local beer stalls, popular with locals for cheap beer and snacks.',
    address: 'Pham Van Dong, Da Nang, Vietnam',
    latitude: 16.0667,
    longitude: 108.2167,
    category: 'nightlife',
    subcategory: 'local',
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    rating: 4.7,
    priceRange: 'low',
    indoor: false,
    outdoor: true,
    weatherDependent: true,
    isAnvaAuthentic: true,
    localRating: 4.9,
  },

  // More Attractions
  {
    name: 'Dragon Bridge',
    description: 'Iconic bridge shaped like a dragon that breathes fire and water on weekends.',
    address: 'Dragon Bridge, Da Nang, Vietnam',
    latitude: 16.0667,
    longitude: 108.2167,
    category: 'attraction',
    subcategory: 'landmark',
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
    rating: 4.6,
    priceRange: 'low',
    indoor: false,
    outdoor: true,
    weatherDependent: false,
    isAnvaAuthentic: false,
    localRating: 4.5,
  },
  {
    name: 'Love Lock Bridge',
    description: 'Romantic bridge where couples attach locks, beautiful views of the Han River.',
    address: 'Han River, Da Nang, Vietnam',
    latitude: 16.0667,
    longitude: 108.2167,
    category: 'attraction',
    subcategory: 'romantic',
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
    rating: 4.5,
    priceRange: 'low',
    indoor: false,
    outdoor: true,
    weatherDependent: true,
    isAnvaAuthentic: false,
    localRating: 4.4,
  },
  {
    name: 'Asia Park',
    description: 'Amusement park with rides, cultural zones, and the Sun Wheel.',
    address: '1 Phan Dang Luu, Da Nang, Vietnam',
    latitude: 16.0667,
    longitude: 108.2167,
    category: 'attraction',
    subcategory: 'theme_park',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    rating: 4.4,
    priceRange: 'medium',
    indoor: true,
    outdoor: true,
    weatherDependent: true,
    isAnvaAuthentic: false,
    localRating: 4.2,
  },
];

async function main() {
  console.log('🌱 Seeding database...');

  // Clear existing locations
  await prisma.location.deleteMany({});
  console.log('✅ Cleared existing locations');

  // Create locations
  for (const location of danangLocations) {
    await prisma.location.create({
      data: location,
    });
  }

  console.log(`✅ Created ${danangLocations.length} locations`);
  console.log('🎉 Seeding completed!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

