// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Note: With Prisma 6, datasource URL is in schema.prisma, not here
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
});
